#source 'https://github.com/ZhaoZhenyuCC/MyRepo.git'

target 'ModuleDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  #pod 'ZYModuleManger'


  # Pods for ModuleDemo

  target 'ModuleDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ModuleDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


